server:
  port: 8100

spring:
  application:
    name: luna-cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 服务注册中心动态路由
      routes:
        - id: payment_routh_node_1  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://luna-provider-payment # load balance 负载均衡
          #uri: http://127.0.0.1:8002  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider-payment/api/payment/get/** # 断言，路径相匹配的进行路由
            - After=2021-01-27T15:28:41.748+08:00[Asia/Shanghai] # 在这个时间之后访问可以通过
            - Before=2022-01-27T15:31:34.296+08:00[Asia/Shanghai] # 在这个时间之前访问可以通过
            - Between=2021-01-27T15:28:41.748+08:00[Asia/Shanghai],2022-01-27T15:31:34.296+08:00[Asia/Shanghai] # 在这个时间之间访问可以通过
            - Cookie=username,luna # 带Cookie访问 正则匹配
            - Header=X-Request-Id,\d+  # 请求头 带参数 正则匹配
            - Host=**.luna.com # 请求头带指定host参数
            - Method=GET
            - Query=id,\d+ # 路径带参数

        - id: payment_routh_node_2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://luna-provider-payment # load balance 负载均衡
          #uri: http://127.0.0.1:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider-payment/api/discovery  # 断言，路径相匹配的进行路由
# 注册进 eureka Server
eureka:
  instance:
    instance-id: luna-cloud-gateway-node
    prefer-ip-address: true
    # 客户端向服务端发送心跳包
    #lease-renewal-interval-in-seconds: 1
    # 客户端最后一次收到服务端心跳包后的最长等待时间
    #lease-expiration-duration-in-seconds: 3
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      defaultZone: http://eurekanodei.com:7001/eureka-server/eureka/
      #defaultZone: http://eurekanodeii.com:7002/eureka-server/eureka/,http://eurekanodei.com:7001/eureka-server/eureka/

