server:
  port: 7002
  servlet:
    context-path: /eureka-server

eureka:
  instance:
    hostname: eurekanodeII.com  # eureka 服务器的实例名称
  client:
    # false 代表不向服务注册中心注册自己，因为它本身就是服务中心
    register-with-eureka: false
    # false 代表自己就是服务注册中心，自己的作用就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
      # 注意这里对<p>servlet:  context-path </p>会影响整个项目根目录，对应对配置注册地址也应该有所改动
      defaultZone: http://eurekanodeI.com:7001/eureka-server/eureka/